### ISSUE TITLE
Use my own hooks

### ISSUE THREAD

**Issue by kkmuffme** [psalm/psalm-plugin-wordpress#28]
Instead of loading only WP core hooks/filters, allow using my own hooks via config options.
This is helpful if I want to e.g. load WooCommerce or any custom plugin hooks that should be checked.

See https://github.com/humanmade/psalm-plugin-wordpress/issues/12#issuecomment-1003797361

**Comment by paulshryock** [comment]
While this is waiting to be included in a future release, is there a way to suppress Psalm to allow non-core hooks?

I tried this:
```php
/** @psalm-suppress HookNotFound */
add_filter(
	'ep_index_name',
	__NAMESPACE__ . '\\Elasticsearch\\set_index_name',
	10,
	3,
);
```

But this throws an error:
```bash
ERROR: HookNotFound - src/php/hooks/add-filters.php:16:1 - Hook ep_index_name not found.
/** @psalm-suppress HookNotFound */
add_filter(
	'ep_index_name',
	__NAMESPACE__ . '\\Elasticsearch\\set_index_name',
	10,
	3,
);
```

**Comment by kraftner** [comment]
@paulshryock I just looked in my codebase and seems like I only found a way to ignore it per file:

```
<PluginIssue name="HookNotFound">
    <errorLevel type="info">
        <file name="src/foo/Bar.php" />
    </errorLevel>
</PluginIssue>
```

**Comment by paulshryock** [comment]
Thanks for the quick replies, @kraftner and @kkmuffme! I've decided to [patch the plugin using cweagans/composer-patches](https://github.com/cweagans/composer-patches) to remove [the `HookNotFound` check](https://github.com/humanmade/psalm-plugin-wordpress/blob/2.0.5/Plugin.php#L247-L257) in my project until the next version of this plugin is released.

This means I lose the benefits of `HookNotFound`, but gain back the ability to use third-party hooks without Psalm errors.
